export const STATUS_OPTIONS = [
  { label: "All", value: "" },
  { label: "Available", value: "available" },
  { label: "Unavailable", value: "unavailable" },
];

export const GEAR_TYPES = [
  { label: "All", value: "" },
  { label: "Automatic", value: "Automatic" },
  { label: "Manual", value: "Manual" },
];

export const FUEL_TYPES = [
  { label: "All", value: "" },
  { label: "Petrol", value: "Petrol" },
  { label: "Diesel", value: "Diesel" },
  { label: "Electric", value: "Electric" },
];

export const CAR_BRANDS = [
  { label: "All", value: "" },
  { label: "Toyota", value: "Toyota" },
  { label: "Honda", value: "Honda" },
  { label: "Ford", value: "Ford" },
  { label: "Nissan", value: "Nissan" },
  { label: "Mitsubishi", value: "Mitsubishi" },
  { label: "BMW", value: "BMW" },
  { label: "Mercedes-Benz", value: "Mercedes-Benz" },
  { label: "Jeep", value: "Jeep" },
  { label: "Hyundai", value: "Hyundai" },
  { label: "Kia", value: "Kia" },
  { label: "Mazda", value: "Mazda" },
  { label: "Subaru", value: "Subaru" },
  { label: "Suzuki", value: "Suzuki" },
  { label: "Isuzu", value: "Isuzu" },
  { label: "Chevrolet", value: "Chevrolet" },
  { label: "GMC", value: "GMC" },
  { label: "Cadillac", value: "Cadillac" },
  { label: "Buick", value: "Buick" },
  { label: "Dodge", value: "Dodge" },
  { label: "Chrysler", value: "Chrysler" },
  { label: "Ram", value: "Ram" },
  { label: "Volkswagen", value: "Volkswagen" },
  { label: "Audi", value: "Audi" },
  { label: "Porsche", value: "Porsche" },
  { label: "Volvo", value: "Volvo" },
  { label: "Lexus", value: "Lexus" },
  { label: "Infiniti", value: "Infiniti" },
  { label: "Acura", value: "Acura" },
  { label: "Genesis", value: "Genesis" },
  { label: "Jaguar", value: "Jaguar" },
  { label: "Land Rover", value: "Land Rover" },
  { label: "Mini", value: "Mini" },
  { label: "Fiat", value: "Fiat" },
  { label: "Alfa Romeo", value: "Alfa Romeo" },
  { label: "Ferrari", value: "Ferrari" },
  { label: "Lamborghini", value: "Lamborghini" },
  { label: "Maserati", value: "Maserati" },
  { label: "Rolls-Royce", value: "Rolls-Royce" },
  { label: "Bentley", value: "Bentley" },
  { label: "Peugeot", value: "Peugeot" },
  { label: "Renault", value: "Renault" },
  { label: "Citroën", value: "Citroën" },
  { label: "Opel", value: "Opel" },
  { label: "Skoda", value: "Skoda" },
  { label: "Seat", value: "Seat" },
  { label: "Tesla", value: "Tesla" },
  { label: "BYD", value: "BYD" },
  { label: "Geely", value: "Geely" },
  { label: "Chery", value: "Chery" },
  { label: "Great Wall", value: "Great Wall" },
  { label: "Haval", value: "Haval" },
  { label: "MG", value: "MG" },
  { label: "Nio", value: "Nio" },
  { label: "Xpeng", value: "Xpeng" },
  { label: "Li Auto", value: "Li Auto" },
  { label: "Wuling", value: "Wuling" },
  { label: "VinFast", value: "VinFast" },
];
